#  Installing Numpy
---
* conda install Numpy from cmd (for anaconda users) 
* pip install Numpy 

# Lists and (numpy) Arrays
---
*  Most numpy operations act element-wise

In [1]:
import numpy as np

In [2]:
#  list 
L = [1,2,3]

In [3]:
#  numpy array
A = np.array([1,2,3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [6]:
#  append to the list
L.append(4)
L

[1, 2, 3, 4]

In [7]:
#  append to the numpy array doesn't work
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
#   appending to list works with addition
L = L + [5]
L

[1, 2, 3, 4, 5]

In [9]:
#  appending with addition errors for np array
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [10]:
#  List element-wise addition
L2 = []
for e in L:
    L2.append(e+e)

L2

[2, 4, 6, 8, 10]

In [11]:
#   Vector element-wise addition in numpy is just +
B=A+A
B

array([2, 4, 6])

In [12]:
#  element wise multiplication of np array
2*A

array([2, 4, 6])

In [13]:
#  mult is not element wise for lists...
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
#  element wise squaring of lists doesn't work
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
#  need to loop through list to square each element. 
L3 = []
for e in L:
    L3.append(e*e)
    
L3

[1, 4, 9, 16, 25]

In [16]:
#  numpy squares element wise in one step
A**2

array([1, 4, 9], dtype=int32)

#  Element Wise Arithmetic 

In [17]:
A

array([1, 2, 3])

In [18]:
#  element-wise square root 
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [19]:
#  element wise log 
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [20]:
#  element wise exponential of np Array
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

#  Dot Product 1:  For loop vs. cosine method vs. dot function