#  Installing Numpy
---
* conda install Numpy from cmd (for anaconda users) 
* pip install Numpy 

# Lists and (numpy) Arrays
---
*  Most numpy operations act element-wise

In [1]:
import numpy as np

In [2]:
#  list 
L = [1,2,3]

In [3]:
#  numpy array
A = np.array([1,2,3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [6]:
#  append to the list
L.append(4)
L

[1, 2, 3, 4]

In [7]:
#  append to the numpy array doesn't work
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
#   appending to list works with addition
L = L + [5]
L

[1, 2, 3, 4, 5]

In [9]:
#  appending with addition errors for np array
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [10]:
#  List element-wise addition
L2 = []
for e in L:
    L2.append(e+e)

L2

[2, 4, 6, 8, 10]

In [11]:
#   Vector element-wise addition in numpy is just +
B=A+A
B

array([2, 4, 6])

In [12]:
#  element wise multiplication of np array
2*A

array([2, 4, 6])

In [13]:
#  mult is not element wise for lists...
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [14]:
#  element wise squaring of lists doesn't work
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
#  need to loop through list to square each element. 
L3 = []
for e in L:
    L3.append(e*e)
    
L3

[1, 4, 9, 16, 25]

In [16]:
#  numpy squares element wise in one step
A**2

array([1, 4, 9], dtype=int32)

#  Element Wise Arithmetic 

In [17]:
A

array([1, 2, 3])

In [18]:
#  element-wise square root 
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [19]:
#  element wise log 
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [20]:
#  element wise exponential of np Array
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

#  Dot Product 1:  For loop vs. cosine method vs. dot function

In [1]:
import numpy as np

In [2]:
a = np.array([1,2])

In [3]:
b = np.array([2,1])

In [4]:
dot = 0 

for e,f in zip(a,b):
    dot += e*f


In [5]:
dot

4

In [7]:
#  element wise mult
a*b

array([2, 2])

In [8]:
np.sum(a*b)

4

In [9]:
(a*b).sum()

4

In [10]:
np.dot(a,b)

4

In [11]:
a.dot(b)

4

## Cos(theta) = A * B / |A||B|
$\begin{equation}
\displaystyle\cos(\theta) = \frac{AB}{\big|A\big|\big|B\big|}
\end{equation}$

In [14]:
amag = np.sqrt((a*a).sum())
amag

2.2360679774997898

In [18]:
amag = np.linalg.norm(a)
amag

2.2360679774997898

In [20]:
cosangle = a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.79999999999999982

In [21]:
angle = np.arccos(cosangle)
angle

0.6435011087932847

# Dot Product Speed Comparision

In [37]:
import numpy as np

from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 10000

def slow_dot_product(a,b):
    result = 0 
    #for e,f in zip(a,b):
        #result += e*f
    for e in range(len(a)):
        result += a[e]*b[e]

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

print('dt1/dt2: ',dt1.total_seconds()/dt2.total_seconds())

dt1/dt2:  61.348470948012235


#  Vectors and Matrices

In [1]:
import numpy as np

In [2]:
M = np.array([[1,2],[3,4]])

In [4]:
#  List of lists
L = [[1,2],[3,4]]

In [5]:
#  L[row][column]
L[0][1]

2

In [6]:
M[0][1]

2

In [7]:
#  numpy also has matlab shorthand notation
#  M[row,column]
M[0,1]

2

In [11]:
#  note the numpy library suggests always using arrays 
np.matrix([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

#  Generating Data Arrays

In [13]:
#  zero 1D array
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
# zero 10x10 matrix (tuple input
Z = np.zeros((10,10)) 
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
# 10x10 matrix of ones 
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [20]:
#  random (0,1) 10x10 array 
R = np.random.random((10,10))
R

array([[ 0.03635986,  0.72753222,  0.6414242 ,  0.43448641,  0.69778873,
         0.44193452,  0.16070658,  0.58077644,  0.13331492,  0.94657278],
       [ 0.45097049,  0.76439474,  0.64709316,  0.76849724,  0.25115979,
         0.52809916,  0.8257384 ,  0.97847725,  0.29779863,  0.76787398],
       [ 0.50978868,  0.27401671,  0.32816553,  0.75973159,  0.85485108,
         0.69015799,  0.78937987,  0.92228957,  0.60218615,  0.71346928],
       [ 0.29360712,  0.51508888,  0.73010182,  0.39223065,  0.45648925,
         0.43187459,  0.42447474,  0.50910174,  0.24872367,  0.26745989],
       [ 0.17520225,  0.89172455,  0.50156596,  0.10555854,  0.00537053,
         0.73293041,  0.70084118,  0.5316438 ,  0.54178299,  0.61542455],
       [ 0.97384838,  0.46606312,  0.57732954,  0.21521047,  0.17663838,
         0.75259792,  0.75779937,  0.30235427,  0.01721604,  0.01472771],
       [ 0.48935789,  0.61130012,  0.29207507,  0.49433515,  0.22468363,
         0.03532941,  0.90679611,  0.73701952

In [21]:
#  gaussian distribution random values
G = np.random.randn(10,10)
G

array([[ -8.63287530e-01,  -4.83533578e-01,  -6.93462221e-01,
         -1.33147343e+00,  -1.06050478e+00,  -1.80012106e+00,
          1.20533566e+00,   7.01888686e-01,  -1.69623748e-03,
          1.55059549e+00],
       [ -3.25009025e-01,   5.59883558e-01,   1.12219769e+00,
         -1.03544818e+00,  -8.67900000e-01,   1.10682386e+00,
          2.15413246e-01,   1.57984225e+00,  -6.96417992e-02,
         -1.02457477e-01],
       [  2.89191144e-01,   1.04019391e+00,   3.83323940e-01,
         -6.36815143e-01,   7.83678056e-01,  -2.00964752e-01,
         -6.24563884e-01,  -8.21223072e-01,   3.35076250e-01,
         -2.42375064e-01],
       [ -2.10370102e-01,  -2.00042547e+00,   1.65475763e+00,
         -4.56202585e-01,  -2.62963922e-01,  -1.10533902e+00,
          1.72364795e+00,   1.86874837e-01,   7.32897262e-01,
          1.08481092e+00],
       [  9.51956885e-01,   1.38870388e+00,  -1.29614184e+00,
          1.51707888e+00,   2.58445295e-01,   3.28348163e-01,
          7.33230608e-01

In [22]:
G.mean()

-0.040672128844723557

In [23]:
#  variance 
G.var()

1.0049474000794694

#  Matrix Product